[package]
name = "soapbox"
version = "0.1.0"
authors = ["Deep Majumder <deep.majumder2019@gmail.com>"]
edition = "2021"

[dependencies]
serialport = "~4"
colored = "~2"
thiserror = "~1"
indicatif = "~0.16"
ctrlc = "~3"
